module: NIOLIFX
author: Paul Schmiedmayer
theme: fullwidth
output: ./docs
documentation: ./*.md
author_url: https://github.com/PSchmiedmayer
github_url: https://github.com/Pschmiedmayer/Swift-NIO-LIFX
