name: Build Docker Image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64,linux/amd64
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        id: buildandpush
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/jass2021/lifx-post-discovery-action:latest,ghcr.io/jass2021/lifx-post-discovery-action:${{ steps.latesttag.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.buildandpush.outputs.digest }}
